name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and deploy to Minikube

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
          driver: docker

      - name: Check cluster
        run: kubectl get pods -A

      - name: Build image
        run: |
          docker build -t devopshint/node-app:latest .

      - name: Load image into Minikube
        run: |
          minikube image load devopshint/node-app:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s-node-app.yaml

      - name: Check deployment
        run: |
          kubectl get pods
          kubectl get services

      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url
